# Importando Bibliotecas e Dataset

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv('../dataset/zomato.csv')

# Limpeza dos Dados

In [3]:
# Criando Funções:

COUNTRIES = {
1: "India",
14: "Australia",
30: "Brazil",
37: "Canada",
94: "Indonesia",
148: "New Zeland",
162: "Philippines",
166: "Qatar",
184: "Singapure",
189: "South Africa",
191: "Sri Lanka",
208: "Turkey",
214: "United Arab Emirates",
215: "England",
216: "United States of America",
}

def Country_Name(country_id):
    return COUNTRIES[country_id]


# -----------------------------------------------


def create_price_tye(price_range):
    if price_range == 1:
        return "cheap"
    elif price_range == 2:
        return "normal"
    elif price_range == 3:
        return "expensive"
    else:
        return "gourmet"


# -----------------------------------------------

COLORS = {
"3F7E00": "darkgreen",
"5BA829": "green",
"9ACD32": "lightgreen",
"CDD614": "orange",
"FFBA00": "red",
"CBCBC8": "darkred",
"FF7800": "darkred",
}
def color_name(color_code):
    return COLORS[color_code]

# -----------------------------------------------

def rename_columns(dataframe):
    df = dataframe.copy()
    title = lambda x: inflection.titleize(x)
    snakecase = lambda x: inflection.underscore(x)
    spaces = lambda x: x.replace(" ", "")
    cols_old = list(df1.columns)
    cols_old = list(map(title, cols_old))
    cols_old = list(map(spaces, cols_old))
    cols_new = list(map(snakecase, cols_old))
    df1.columns = cols_new
    return df

In [4]:
# Define categorias de preço de acordo com o range
df['price_category'] = df['Price range'].apply(create_price_tye)

# Define o padrão de cores das avaliações
df['rating_color'] = df['Rating color'].apply(color_name)

# --------------------------------------------------------

df['country_name'] = df['Country Code'].map(Country_Name)
# Definisdo os restaurantes po apenas um tipo de culinaria
df["Cuisines"] = df.loc[:, "Cuisines"].astype(str).apply(lambda x: x.split(",")[0])

# Deletando coluna desnecessária, todos os valores são 0
df = df.drop(['Switch to order menu'], axis=1)

# Deixando todas as colunas em formato snake_case

df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

# --------------------------------------------------------

# Verificar quanto em % representa os dados nulos

df.isna().mean() * 100

# Dropando todos os dados nulos

df = df.dropna()

In [5]:
# Verificar se há linhas duplicadas

print(df.duplicated().sum())

# Dropando as linhas duplicadas e salvando direto no dataset

df.drop_duplicates(inplace=True)

# Verificando novamente se há linhas duplicadas

print(df.duplicated().sum())

585
0

# Analisando o Dataset

In [6]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,...,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,price_category,rating_color,country_name
0,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,0,0,3,4.6,3F7E00,Excellent,619,expensive,darkgreen,Philippines
2,6314542,Blackbird,162,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,European,...,0,0,4,4.7,3F7E00,Excellent,469,gourmet,darkgreen,Philippines
3,6301293,Banapple,162,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,Filipino,...,0,0,3,4.4,5BA829,Very Good,867,expensive,green,Philippines
4,6315689,Bad Bird,162,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,...,0,0,3,4.4,5BA829,Very Good,858,expensive,green,Philippines
5,6304833,Manam,162,Makati City,"Level 1, Greenbelt 2, Ayala Center, Greenbelt,...","Greenbelt 2, San Lorenzo, Makati City","Greenbelt 2, San Lorenzo, Makati City, Makati ...",121.020380,14.552351,Filipino,...,0,0,3,4.7,3F7E00,Excellent,930,expensive,darkgreen,Philippines

In [7]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'country_code', 'city', 'address',
       'locality', 'locality_verbose', 'longitude', 'latitude', 'cuisines',
       'average_cost_for_two', 'currency', 'has_table_booking',
       'has_online_delivery', 'is_delivering_now', 'price_range',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'price_category', 'rating_color', 'country_name'],
      dtype='object')

In [8]:
df.shape

(6942, 23)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6942 entries, 0 to 7526
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_id         6942 non-null   int64
 1   restaurant_name       6942 non-null   object
 2   country_code          6942 non-null   int64
 3   city                  6942 non-null   object
 4   address               6942 non-null   object
 5   locality              6942 non-null   object
 6   locality_verbose      6942 non-null   object
 7   longitude             6942 non-null   float64
 8   latitude              6942 non-null   float64
 9   cuisines              6942 non-null   object
 10  average_cost_for_two  6942 non-null   int64
 11  currency              6942 non-null   object
 12  has_table_booking     6942 non-null   int64
 13  has_online_delivery   6942 non-null   int64
 14  is_delivering_now     6942 non-null   int64
 15  price_range           6942 non-null   int64
 16  aggregate_rating      6942 non-null   float64
 17  rating_color          6942 non-null   object
 18  rating_text           6942 non-null   object
 19  votes                 6942 non-null   int64
 20  price_category        6942 non-null   object
 21  rating_color          6942 non-null   object
 22  country_name          6942 non-null   object
dtypes: float64(3), int64(8), object(12)
memory usage: 1.3+ MB

In [10]:
df.describe()

,restaurant_id,country_code,longitude,latitude,average_cost_for_two,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,votes
count,6.942000e+03,6942.000000,6942.000000,6942.000000,6.942000e+03,6942.000000,6942.000000,6942.000000,6942.000000,6942.000000,6942.000000
mean,1.076193e+07,95.785941,31.441225,19.434945,7.506579e+03,0.060501,0.349755,0.174589,2.632383,4.126765,604.384039
std,7.037688e+06,99.299120,79.059108,23.499885,3.022515e+05,0.238430,0.476927,0.379643,0.966060,0.674754,1115.744044
min,5.490000e+02,1.000000,-122.700455,-41.330428,0.000000e+00,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.600075e+06,1.000000,-43.225469,12.902646,6.000000e+01,0.000000,0.000000,0.000000,2.000000,4.000000,150.000000
50%,7.900186e+06,30.000000,73.758624,25.270021,2.500000e+02,0.000000,0.000000,0.000000,3.000000,4.200000,328.000000
75%,1.714692e+07,215.000000,79.832568,32.749289,6.000000e+02,0.000000,1.000000,0.000000,3.000000,4.500000,649.000000
max,1.904028e+07,216.000000,175.310552,55.976980,2.500002e+07,1.000000,1.000000,1.000000,4.000000,4.900000,41333.000000

# Perguntas de Negócio

### 1. Dos restaurantes que possuem o tipo de culinária italiana, qual o nome do restaurante com a maior média de avaliação?

In [16]:
df_italiana = (df.loc[ df['cuisines'] == 'Italian' , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   maior_media=('aggregate_rating', 'max'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['maior_media', 'menor_id'],ascending=[False, True]).reset_index().iloc[0])
nome = df_italiana['restaurant_name']
maior_media = df_italiana['maior_media']

print(f'O restaurante com a culinária do tipo italiana e com a maior média é {nome}, com {maior_media}')

O restaurante com a culinária do tipo italiana e com a maior média é Darshan, com 4.9

### 2. Dos restaurantes que possuem o tipo de culinária italiana, qual o nome do restaurante com a menor média de avaliação?

In [20]:
df_italiana = (df.loc[ (df['cuisines'] == 'Italian') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   menor_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['menor_media', 'menor_id'],ascending=[True, True]).reset_index().iloc[0])
nome = df_italiana['restaurant_name']
menor_media = df_italiana['menor_media']

print(f'O restaurante com a culinária do tipo italiana e com a menor média é {nome}, com {menor_media}')

O restaurante com a culinária do tipo italiana e com a menor média é Siena's, com 2.3

### 3. Dos restaurantes que possuem o tipo de culinária americana, qual o nome do restaurante com a maior média de avaliação?

In [23]:
df_americana = (df.loc[ (df['cuisines'] == 'American') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   maior_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['maior_media', 'menor_id'],ascending=[False, True]).reset_index().iloc[0])
nome = df_americana['restaurant_name']
maior_media = df_americana['maior_media']

print(f'O restaurante com a culinária do tipo americana e com a maior média é {nome}, com {maior_media}')

O restaurante com a culinária do tipo americana e com a maior média é OEB Breakfast Co., com 4.9

### 4. Dos restaurantes que possuem o tipo de culinária americana, qual o nome do restaurante com a menor média de avaliação?

In [30]:
df_americana = (df.loc[ (df['cuisines'] == 'American') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   menor_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['menor_media', 'menor_id'],ascending=[True, True]).reset_index().iloc[0])
nome = df_americana['restaurant_name']
menor_media = df_americana['menor_media']

print(f'O restaurante com a culinária do tipo americana e com a menor média é {nome}, com {menor_media}')

O restaurante com a culinária do tipo americana e com a menor média é Guy Fieri's Kitchen & Bar, com 2.2

### 5. Dos restaurantes que possuem o tipo de culinária árabe, qual o nome do restaurante com a maior média de avaliação?

In [27]:
df_arabe = (df.loc[ (df['cuisines'] == 'Arabian') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   maior_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['maior_media', 'menor_id'],ascending=[False, True]).reset_index().iloc[0])
nome = df_arabe['restaurant_name']
maior_media = df_arabe['maior_media']

print(f'O restaurante com a culinária do tipo arabe e com a maior média é {nome}, com {maior_media}')

O restaurante com a culinária do tipo arabe e com a maior média é Mandi@36, com 4.7

### 6. Dos restaurantes que possuem o tipo de culinária árabe, qual o nome do restaurante com a menor média de avaliação?

In [29]:
df_arabe = (df.loc[ (df['cuisines'] == 'Arabian') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   menor_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['menor_media', 'menor_id'],ascending=[True, True]).reset_index().iloc[0])
nome = df_arabe['restaurant_name']
menor_media = df_arabe['menor_media']

print(f'O restaurante com a culinária do tipo arabe e com a menor média é {nome}, com {menor_media}')

O restaurante com a culinária do tipo arabe e com a menor média é Empório Árabe, com 2.7

### 7. Dos restaurantes que possuem o tipo de culinária japonesa, qual o nome do restaurante com a maior média de avaliação?

In [34]:
df_japonesa = (df.loc[ (df['cuisines'] == 'Japanese') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   maior_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['maior_media', 'menor_id'],ascending=[False, True]).reset_index().iloc[0])
nome = df_japonesa['restaurant_name']
maior_media = df_japonesa['maior_media']

print(f'O restaurante com a culinária do tipo japonesa e com a maior média é {nome}, com {maior_media}')

O restaurante com a culinária do tipo japonesa e com a maior média é Sushi Samba, com 4.9

### 8. Dos restaurantes que possuem o tipo de culinária japonesa, qual o nome do restaurante com a menor média de avaliação?

In [32]:
df_japonesa = (df.loc[ (df['cuisines'] == 'Japanese') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   menor_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['menor_media', 'menor_id'],ascending=[True, True]).reset_index().iloc[0])
nome = df_japonesa['restaurant_name']
menor_media = df_japonesa['menor_media']

print(f'O restaurante com a culinária do tipo japonesa e com a menor média é {nome}, com {menor_media}')

O restaurante com a culinária do tipo japonesa e com a menor média é Orienthai, com 2.4

### 9. Dos restaurantes que possuem o tipo de culinária caseira, qual o nome do restaurante com a maior média de avaliação

In [36]:
df_caseira = (df.loc[ (df['cuisines'] == 'Home-made') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   maior_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['maior_media', 'menor_id'],ascending=[False, True]).reset_index().iloc[0])
nome = df_caseira['restaurant_name']
maior_media = df_caseira['maior_media']

print(f'O restaurante com a culinária do tipo caseira e com a maior média é {nome}, com {maior_media}')

O restaurante com a culinária do tipo caseira e com a maior média é Kanaat Lokantası, com 4.0

### 10. Dos restaurantes que possuem o tipo de culinária caseira, qual o nome do restaurante com a menor média de avaliação?

In [35]:
df_caseira = (df.loc[ (df['cuisines'] == 'Home-made') & (df['aggregate_rating'] > 0.0) , ['restaurant_name' , 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
               .agg(
                   menor_media=('aggregate_rating', 'min'),
                   menor_id=('restaurant_id', 'min')
               ) .sort_values(by= ['menor_media', 'menor_id'],ascending=[True, True]).reset_index().iloc[0])
nome = df_caseira['restaurant_name']
menor_media = df_caseira['menor_media']

print(f'O restaurante com a culinária do tipo caseira e com a menor média é {nome}, com {menor_media}')

O restaurante com a culinária do tipo caseira e com a menor média é GurMekan Restaurant, com 3.7

### 11. Qual o tipo de culinária que possui o maior valor médio de um prato para duas pessoas?

In [41]:
culinaria_duas_pessoas = df.loc[ : , ['cuisines', 'average_cost_for_two']].groupby('cuisines')['average_cost_for_two'].mean().sort_values(ascending=False).reset_index().iloc[0]
nome = culinaria_duas_pessoas['cuisines']

print(f'O tipo de culinária com o maior valor médio de um prato para duas pessoas é {nome}')

O tipo de culinária com o maior valor médio de um prato para duas pessoas é Modern Australian

### 12. Qual o tipo de culinária que possui a maior nota média?

In [53]:
culinaria_nota_media = (df.loc[ : , ['cuisines', 'aggregate_rating', 'restaurant_id']].groupby('cuisines')
                        .agg(
                            maior_nota = ('aggregate_rating', 'max'),
                            menor_id = ('restaurant_id', 'min')
                        ).sort_values(by=['maior_nota', 'menor_id'] , ascending=[False, True]).reset_index().iloc[0])
nome = culinaria_nota_media['cuisines']
nota = culinaria_nota_media['maior_nota']

print(f'O tipo de culinária com a maior nota é {nome}, com média {nota}')

O tipo de culinária com a maior nota é North Indian, com média 4.9

### 13. Qual o tipo de culinária que possui mais restaurantes que aceitam pedidos online e fazem entregas?

In [59]:
culinaria_online_entrega = df.loc[ (df['has_online_delivery'] == 1) & (df['is_delivering_now'] == 1) , ['cuisines', 'restaurant_id']].groupby('cuisines')['restaurant_id'].count().sort_values(ascending=False).reset_index().iloc[0]
nome = culinaria_online_entrega['cuisines']

print(f'O tipo de culinária que possui mais restaurantes que aceitam pedidos online e fazem entrega é {nome}')

O tipo de culinária que possui mais restaurantes que aceitam pedidos online e fazem entrega é North Indian

# Funções e Gráficos

In [ ]:
# Top 10 melhores restaurantes

def top_restaurantes(df):
    cols = ['restaurant_id','restaurant_name','country_name','city','cuisines','average_cost_for_two','aggregate_rating','votes']

    top = (df.loc[:, cols].groupby('restaurant_name')
           .agg({'restaurant_id':'min','country_name':'first','city':'first','cuisines':'first',
                 'average_cost_for_two':'first','aggregate_rating':'mean','votes':'sum'})
           .reset_index()
           .sort_values(by=['aggregate_rating','votes','restaurant_id'],
                        ascending=[False, False, True])
           .head(10))

    return top

top_restaurantes(df)

In [ ]:
# Top 10 melhores culinarias
def top_culinarias(df):
    culinaria_nota_media = (df.loc[ : , ['cuisines', 'aggregate_rating', 'restaurant_id', 'country_name']].groupby('cuisines')
                            .agg(
                                maior_nota = ('aggregate_rating', 'max'),
                                menor_id = ('restaurant_id', 'min'),
                                country_name=('country_name', 'first')
                            ).sort_values(by=['maior_nota', 'menor_id'] , ascending=[False, True]).reset_index().head(10))
    
    fig = px.bar(culinaria_nota_media, x='cuisines', y='maior_nota', text='maior_nota', labels={'country_name': 'Países'} )
    fig.update_layout(
                      xaxis_title='Culinária',
                      yaxis_title='Média Nota'
                      )
    
    fig.update_traces(textposition='outside')

    return fig

top_culinarias(df)

In [ ]:
# Top 10 piores culinarias

def top_culinarias(df):
    culinaria_nota_media = (df.loc[ : , ['cuisines', 'aggregate_rating', 'restaurant_id', 'country_name']].groupby('cuisines')
                            .agg(
                                menor_nota = ('aggregate_rating', 'min'),
                                menor_id = ('restaurant_id', 'min'),
                                country_name=('country_name', 'first')
                            ).sort_values(by=['menor_nota', 'menor_id'] , ascending=[False, True]).reset_index().head(10))
    
    fig = px.bar(culinaria_nota_media, x='cuisines', y='menor_nota', text='menor_nota', labels={'country_name': 'Países'} )
    fig.update_layout(
                      xaxis_title='Culinária',
                      yaxis_title='Média Nota'
                      )
    
    fig.update_traces(textposition='outside')

    return fig

top_culinarias(df)