# Importando Bibliotecas e Dataset

In [2]:
import pandas as pd
import plotly.express as px

In [3]:
df = pd.read_csv('../dataset/zomato.csv')

# Limpeza dos Dados

In [4]:
# Criando Funções:

COUNTRIES = {
1: "India",
14: "Australia",
30: "Brazil",
37: "Canada",
94: "Indonesia",
148: "New Zeland",
162: "Philippines",
166: "Qatar",
184: "Singapure",
189: "South Africa",
191: "Sri Lanka",
208: "Turkey",
214: "United Arab Emirates",
215: "England",
216: "United States of America",
}

def Country_Name(country_id):
    return COUNTRIES[country_id]


# -----------------------------------------------


def create_price_tye(price_range):
    if price_range == 1:
        return "cheap"
    elif price_range == 2:
        return "normal"
    elif price_range == 3:
        return "expensive"
    else:
        return "gourmet"


# -----------------------------------------------

COLORS = {
"3F7E00": "darkgreen",
"5BA829": "green",
"9ACD32": "lightgreen",
"CDD614": "orange",
"FFBA00": "red",
"CBCBC8": "darkred",
"FF7800": "darkred",
}
def color_name(color_code):
    return COLORS[color_code]

# -----------------------------------------------

def rename_columns(dataframe):
    df = dataframe.copy()
    title = lambda x: inflection.titleize(x)
    snakecase = lambda x: inflection.underscore(x)
    spaces = lambda x: x.replace(" ", "")
    cols_old = list(df1.columns)
    cols_old = list(map(title, cols_old))
    cols_old = list(map(spaces, cols_old))
    cols_new = list(map(snakecase, cols_old))
    df1.columns = cols_new
    return df

In [5]:
# Define categorias de preço de acordo com o range
df['price_category'] = df['Price range'].apply(create_price_tye)

# Define o padrão de cores das avaliações
df['rating_color'] = df['Rating color'].apply(color_name)

# --------------------------------------------------------

df['country_name'] = df['Country Code'].map(Country_Name)
# Definisdo os restaurantes po apenas um tipo de culinaria
df["Cuisines"] = df.loc[:, "Cuisines"].astype(str).apply(lambda x: x.split(",")[0])

# Deletando coluna desnecessária, todos os valores são 0
df = df.drop(['Switch to order menu'], axis=1)

# Deixando todas as colunas em formato snake_case

df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

# --------------------------------------------------------

# Verificar quanto em % representa os dados nulos

df.isna().mean() * 100

# Dropando todos os dados nulos

df = df.dropna()

In [6]:
# Verificar se há linhas duplicadas

print(df.duplicated().sum())

# Dropando as linhas duplicadas e salvando direto no dataset

df.drop_duplicates(inplace=True)

# Verificando novamente se há linhas duplicadas

print(df.duplicated().sum())

585
0

# Analisando o Dataset

In [7]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,...,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,price_category,rating_color,country_name
0,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,0,0,3,4.6,3F7E00,Excellent,619,expensive,darkgreen,Philippines
2,6314542,Blackbird,162,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,European,...,0,0,4,4.7,3F7E00,Excellent,469,gourmet,darkgreen,Philippines
3,6301293,Banapple,162,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,Filipino,...,0,0,3,4.4,5BA829,Very Good,867,expensive,green,Philippines
4,6315689,Bad Bird,162,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,...,0,0,3,4.4,5BA829,Very Good,858,expensive,green,Philippines
5,6304833,Manam,162,Makati City,"Level 1, Greenbelt 2, Ayala Center, Greenbelt,...","Greenbelt 2, San Lorenzo, Makati City","Greenbelt 2, San Lorenzo, Makati City, Makati ...",121.020380,14.552351,Filipino,...,0,0,3,4.7,3F7E00,Excellent,930,expensive,darkgreen,Philippines

In [8]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'country_code', 'city', 'address',
       'locality', 'locality_verbose', 'longitude', 'latitude', 'cuisines',
       'average_cost_for_two', 'currency', 'has_table_booking',
       'has_online_delivery', 'is_delivering_now', 'price_range',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'price_category', 'rating_color', 'country_name'],
      dtype='object')

In [9]:
df.shape

(6942, 23)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6942 entries, 0 to 7526
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_id         6942 non-null   int64
 1   restaurant_name       6942 non-null   object
 2   country_code          6942 non-null   int64
 3   city                  6942 non-null   object
 4   address               6942 non-null   object
 5   locality              6942 non-null   object
 6   locality_verbose      6942 non-null   object
 7   longitude             6942 non-null   float64
 8   latitude              6942 non-null   float64
 9   cuisines              6942 non-null   object
 10  average_cost_for_two  6942 non-null   int64
 11  currency              6942 non-null   object
 12  has_table_booking     6942 non-null   int64
 13  has_online_delivery   6942 non-null   int64
 14  is_delivering_now     6942 non-null   int64
 15  price_range           6942 non-null   int64
 16  aggregate_rating      6942 non-null   float64
 17  rating_color          6942 non-null   object
 18  rating_text           6942 non-null   object
 19  votes                 6942 non-null   int64
 20  price_category        6942 non-null   object
 21  rating_color          6942 non-null   object
 22  country_name          6942 non-null   object
dtypes: float64(3), int64(8), object(12)
memory usage: 1.3+ MB

In [11]:
df.describe()

,restaurant_id,country_code,longitude,latitude,average_cost_for_two,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,votes
count,6.942000e+03,6942.000000,6942.000000,6942.000000,6.942000e+03,6942.000000,6942.000000,6942.000000,6942.000000,6942.000000,6942.000000
mean,1.076193e+07,95.785941,31.441225,19.434945,7.506579e+03,0.060501,0.349755,0.174589,2.632383,4.126765,604.384039
std,7.037688e+06,99.299120,79.059108,23.499885,3.022515e+05,0.238430,0.476927,0.379643,0.966060,0.674754,1115.744044
min,5.490000e+02,1.000000,-122.700455,-41.330428,0.000000e+00,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.600075e+06,1.000000,-43.225469,12.902646,6.000000e+01,0.000000,0.000000,0.000000,2.000000,4.000000,150.000000
50%,7.900186e+06,30.000000,73.758624,25.270021,2.500000e+02,0.000000,0.000000,0.000000,3.000000,4.200000,328.000000
75%,1.714692e+07,215.000000,79.832568,32.749289,6.000000e+02,0.000000,1.000000,0.000000,3.000000,4.500000,649.000000
max,1.904028e+07,216.000000,175.310552,55.976980,2.500002e+07,1.000000,1.000000,1.000000,4.000000,4.900000,41333.000000

# Perguntas de Negócio

### 1. Qual o nome do país que possui mais cidades registradas?

In [13]:
cols = ['country_name', 'city']

paises_agrupados = df.loc[ : , cols].groupby('country_name')['city'].count().sort_values(ascending=False).reset_index(name='Quantidade de Cidades').iloc[0]
nome = paises_agrupados['country_name']
qtd_cidades = paises_agrupados['Quantidade de Cidades']

print(f'O país com mais cidades registradas é a {nome}, com {qtd_cidades} registros')

O país com mais cidades registradas é a India, com 3120 registros

### 2. Qual o nome do país que possui mais restaurantes registrados?

In [14]:
cols = ['country_name', 'restaurant_id']

paises_agrupados = df.loc[ : , cols].groupby('country_name')['restaurant_id'].count().sort_values(ascending=False).reset_index(name='Quantidade de Restaurantes').iloc[0]
nome = paises_agrupados['country_name']
qtd_paises = paises_agrupados['Quantidade de Restaurantes']

print(f'O país com mais restaurantes registradas é a {nome}, com {qtd_paises} registros')

O país com mais restaurantes registradas é a India, com 3120 registros

### 3. Qual o nome do país que possui mais restaurantes com o nível de categoria igual a Gourmet registrados?

In [16]:
contagem_paises = df.loc[df['price_category'] == 'gourmet' , ['country_name' , 'restaurant_id']].groupby('country_name')['restaurant_id'].nunique().sort_values(ascending=False).reset_index(name='Quantidade de Restaurantes').iloc[0]
nome = contagem_paises['country_name']
qtd_restaurantes = contagem_paises['Quantidade de Restaurantes']

print(f'O país com mais restaurantes de nível Gourmet é {nome}, com {qtd_restaurantes} registrados')

O país com mais restaurantes de nível Gourmet é United States of America, com 417 registrados

### 4. Qual o nome do país que possui a maior quantidade de tipos de culinária distintos?

In [17]:
paises_agrupados = df.loc[ : , ['country_name', 'cuisines']].groupby('country_name')['cuisines'].nunique().sort_values(ascending=False).reset_index(name='Quantidade de Tipos Culinários').iloc[0]
nome = paises_agrupados['country_name']
qtd_tipos = paises_agrupados['Quantidade de Tipos Culinários']

print(f'O país com a maior quantidade de tipos culinários é {nome}, com {qtd_tipos} tipos')

O país com a maior quantidade de tipos culinários é India, com 78 tipos

### 5. Qual o nome do país que possui a maior quantidade de avaliações feitas?

In [18]:
paises_agrupados = df.loc [ : , ['country_name', 'votes']].groupby('country_name')['votes'].sum().sort_values(ascending=False).reset_index(name='Quantidade de Avaliacoes').iloc[0]
nome = paises_agrupados['country_name']
qtd_avaliacoes = paises_agrupados['Quantidade de Avaliacoes']

print(f'O país com a maior quantidade de avaliações é {nome}, com {qtd_avaliacoes} no total')

O país com a maior quantidade de avaliações é India, com 2800199 no total

### 6. Qual o nome do país que possui a maior quantidade de restaurantes que fazem entrega?

In [20]:
df_entrega = df.loc[ df['has_online_delivery'] == 1 , ['country_name', 'restaurant_id']].groupby('country_name')['restaurant_id'].nunique().sort_values(ascending=False).reset_index(name='Quantidade de Restaurantes').iloc[0]
nome = df_entrega['country_name']
qtd_restaurantes = df_entrega['Quantidade de Restaurantes']

print(f'O país com a maior quantidade de restaurante que fazem entrega é {nome}, com {qtd_restaurantes} restaurantes')

O país com a maior quantidade de restaurante que fazem entrega é India, com 2177 restaurantes

### 7. Qual o nome do país que possui a maior quantidade de restaurantes que aceitam reservas?

In [21]:
df_reserva= df.loc[ df['has_table_booking'] == 1 , ['country_name', 'restaurant_id']].groupby('country_name')['restaurant_id'].nunique().sort_values(ascending=False).reset_index(name='Quantidade de Restaurantes').iloc[0]
nome = df_reserva['country_name']
qtd_restaurantes = df_reserva['Quantidade de Restaurantes']

print(f'O país com a maior quantidade de restaurante que aceitam reserva é {nome}, com {qtd_restaurantes} restaurantes')

O país com a maior quantidade de restaurante que aceitam reserva é India, com 256 restaurantes

### 8. Qual o nome do país que possui, na média, a maior quantidade de avaliações registrada?

In [22]:
paises_agrupados = df.loc[:, ['country_name', 'votes']].groupby('country_name')['votes'].mean().sort_values(ascending=False).reset_index(name='Quantidade de Avaliacoes Media').iloc[0]
nome = paises_agrupados['country_name']
qtd_avaliacoes = paises_agrupados['Quantidade de Avaliacoes Media']

print(f'O país com a média de maior avaliações registradas é {nome}, com {qtd_avaliacoes:.1f} de média')

O país com a média de maior avaliações registradas é Indonesia, com 1112.8 de média

### 9 . Qual o nome do país que possui, na média, a maior nota média registrada?

In [23]:
paises_agrupados = df.loc [ : , ['country_name', 'aggregate_rating']].groupby('country_name')['aggregate_rating'].mean().sort_values(ascending=False).reset_index(name='Maior Nota Media').iloc[0]
nome = paises_agrupados['country_name']
maior_media = paises_agrupados['Maior Nota Media']

print(f'O país com a maior média registrada é {nome}, com {maior_media:.1f} de média')

O país com a maior média registrada é Indonesia, com 4.6 de média

### 10. Qual o nome do país que possui, na média, a menor nota média registrada?

In [24]:
paises_agrupados = df.loc [ : , ['country_name', 'aggregate_rating']].groupby('country_name')['aggregate_rating'].mean().sort_values(ascending=True).reset_index(name='Menor Nota Media').iloc[0]
nome = paises_agrupados['country_name']
menor_media = paises_agrupados['Menor Nota Media']

print(f'O país com a menor média registrada é {nome}, com {maior_media:.1f} de média')

O país com a menor média registrada é Brazil, com 4.6 de média

### 11. Qual a média de preço de um prato para dois por país?

In [25]:
media_preco = df.groupby('country_name')['average_cost_for_two'].mean().sort_values(ascending=False).reset_index(name='Media de Preco Prato para Dois').round(1)
media_preco

                country_name  Media de Preco Prato para Dois
0                  Indonesia                        303000.0
1                  Australia                        138959.8
2                  Sri Lanka                          2579.4
3                Philippines                          1227.8
4                      India                           703.6
5               South Africa                           339.2
6                      Qatar                           174.0
7       United Arab Emirates                           153.7
8                  Singapure                           141.4
9                     Brazil                           138.8
10                    Turkey                           128.6
11                New Zeland                            62.2
12  United States of America                            55.0
13                   England                            43.5
14                    Canada                            41.9

# Funções de Gráficos

In [47]:
# Quantidade de restraurantes registrados por país

def agrupar_restaurante_pais(df):
  df_restaurantes = df.groupby('country_name')['restaurant_id'].nunique().sort_values(ascending=False).reset_index(name='Quantidade de Restaurantes')
  fig = px.bar(df_restaurantes, x='country_name', y='Quantidade de Restaurantes', text='Quantidade de Restaurantes', color='country_name', labels={'country_name': 'País'})

  fig.update_layout(xaxis_title='Países', showlegend=False)
  
  return fig

agrupar_restaurante_pais(df)

In [48]:
# Quantidade de cidades registradas por país

def agrupar_cidade_pais(df):
  df_cidade_pais = df.groupby('country_name')['city'].nunique().sort_values(ascending=False).reset_index(name='Quantidade de Cidades')
  fig = px.bar(df_cidade_pais, x='country_name', y='Quantidade de Cidades', text='Quantidade de Cidades', color='country_name', labels={'country_name': 'País'})
  
  fig.update_layout(xaxis_title='Países', showlegend=False)

  return fig

agrupar_cidade_pais(df)

In [43]:
# Média de avaliações por pais

def avaliacao_media_pais(df):
  df_media_pais = df.groupby('country_name')['votes'].mean().sort_values(ascending=False).reset_index(name='Media de Avaliacoes').round(2)
  fig = px.bar(df_media_pais, x='country_name', y='Media de Avaliacoes', text='Media de Avaliacoes', color='country_name', labels={'country_name': 'País'})
  
  fig.update_layout(xaxis_title='Países', showlegend=False)

  return fig

avaliacao_media_pais(df)

In [45]:
# Média de preço de um prato pra duas pessoas por país

def media_prato_dois(df):
  df_media_prato_dois = df.groupby('country_name')['average_cost_for_two'].mean().sort_values(ascending=False).reset_index(name='Media Prato para Dois').round(2)
  fig = px.bar(df_media_prato_dois, x='country_name', y='Media Prato para Dois', text='Media Prato para Dois')

  fig.update_layout(xaxis_title='Países')
  

  return fig

media_prato_dois(df)