# Importando Bibliotecas e Dataset

In [3]:
import pandas as pd
import plotly.express as px

In [4]:
df = pd.read_csv('../dataset/zomato.csv')

# Limpeza dos Dados

In [5]:
# Criando Funções:

COUNTRIES = {
1: "India",
14: "Australia",
30: "Brazil",
37: "Canada",
94: "Indonesia",
148: "New Zeland",
162: "Philippines",
166: "Qatar",
184: "Singapure",
189: "South Africa",
191: "Sri Lanka",
208: "Turkey",
214: "United Arab Emirates",
215: "England",
216: "United States of America",
}

def Country_Name(country_id):
    return COUNTRIES[country_id]


# -----------------------------------------------


def create_price_tye(price_range):
    if price_range == 1:
        return "cheap"
    elif price_range == 2:
        return "normal"
    elif price_range == 3:
        return "expensive"
    else:
        return "gourmet"


# -----------------------------------------------

COLORS = {
"3F7E00": "darkgreen",
"5BA829": "green",
"9ACD32": "lightgreen",
"CDD614": "orange",
"FFBA00": "red",
"CBCBC8": "darkred",
"FF7800": "darkred",
}
def color_name(color_code):
    return COLORS[color_code]

# -----------------------------------------------

def rename_columns(dataframe):
    df = dataframe.copy()
    title = lambda x: inflection.titleize(x)
    snakecase = lambda x: inflection.underscore(x)
    spaces = lambda x: x.replace(" ", "")
    cols_old = list(df1.columns)
    cols_old = list(map(title, cols_old))
    cols_old = list(map(spaces, cols_old))
    cols_new = list(map(snakecase, cols_old))
    df1.columns = cols_new
    return df

In [6]:
# Define categorias de preço de acordo com o range
df['price_category'] = df['Price range'].apply(create_price_tye)

# Define o padrão de cores das avaliações
df['rating_color'] = df['Rating color'].apply(color_name)

# --------------------------------------------------------

df['country_name'] = df['Country Code'].map(Country_Name)
# Definisdo os restaurantes po apenas um tipo de culinaria
df["Cuisines"] = df.loc[:, "Cuisines"].astype(str).apply(lambda x: x.split(",")[0])

# Deletando coluna desnecessária, todos os valores são 0
df = df.drop(['Switch to order menu'], axis=1)

# Deixando todas as colunas em formato snake_case

df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_')

# --------------------------------------------------------

# Verificar quanto em % representa os dados nulos

df.isna().mean() * 100

# Dropando todos os dados nulos

df = df.dropna()

In [7]:
# Verificar se há linhas duplicadas

print(df.duplicated().sum())

# Dropando as linhas duplicadas e salvando direto no dataset

df.drop_duplicates(inplace=True)

# Verificando novamente se há linhas duplicadas

print(df.duplicated().sum())

585
0

# Analisando o Dataset

In [8]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,...,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,price_category,rating_color,country_name
0,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,0,0,3,4.6,3F7E00,Excellent,619,expensive,darkgreen,Philippines
2,6314542,Blackbird,162,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,European,...,0,0,4,4.7,3F7E00,Excellent,469,gourmet,darkgreen,Philippines
3,6301293,Banapple,162,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,Filipino,...,0,0,3,4.4,5BA829,Very Good,867,expensive,green,Philippines
4,6315689,Bad Bird,162,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,...,0,0,3,4.4,5BA829,Very Good,858,expensive,green,Philippines
5,6304833,Manam,162,Makati City,"Level 1, Greenbelt 2, Ayala Center, Greenbelt,...","Greenbelt 2, San Lorenzo, Makati City","Greenbelt 2, San Lorenzo, Makati City, Makati ...",121.020380,14.552351,Filipino,...,0,0,3,4.7,3F7E00,Excellent,930,expensive,darkgreen,Philippines

In [9]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'country_code', 'city', 'address',
       'locality', 'locality_verbose', 'longitude', 'latitude', 'cuisines',
       'average_cost_for_two', 'currency', 'has_table_booking',
       'has_online_delivery', 'is_delivering_now', 'price_range',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'price_category', 'rating_color', 'country_name'],
      dtype='object')

In [10]:
df.shape

(6942, 23)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6942 entries, 0 to 7526
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_id         6942 non-null   int64
 1   restaurant_name       6942 non-null   object
 2   country_code          6942 non-null   int64
 3   city                  6942 non-null   object
 4   address               6942 non-null   object
 5   locality              6942 non-null   object
 6   locality_verbose      6942 non-null   object
 7   longitude             6942 non-null   float64
 8   latitude              6942 non-null   float64
 9   cuisines              6942 non-null   object
 10  average_cost_for_two  6942 non-null   int64
 11  currency              6942 non-null   object
 12  has_table_booking     6942 non-null   int64
 13  has_online_delivery   6942 non-null   int64
 14  is_delivering_now     6942 non-null   int64
 15  price_range           6942 non-null   int64
 16  aggregate_rating      6942 non-null   float64
 17  rating_color          6942 non-null   object
 18  rating_text           6942 non-null   object
 19  votes                 6942 non-null   int64
 20  price_category        6942 non-null   object
 21  rating_color          6942 non-null   object
 22  country_name          6942 non-null   object
dtypes: float64(3), int64(8), object(12)
memory usage: 1.3+ MB

In [12]:
df.describe()

,restaurant_id,country_code,longitude,latitude,average_cost_for_two,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,votes
count,6.942000e+03,6942.000000,6942.000000,6942.000000,6.942000e+03,6942.000000,6942.000000,6942.000000,6942.000000,6942.000000,6942.000000
mean,1.076193e+07,95.785941,31.441225,19.434945,7.506579e+03,0.060501,0.349755,0.174589,2.632383,4.126765,604.384039
std,7.037688e+06,99.299120,79.059108,23.499885,3.022515e+05,0.238430,0.476927,0.379643,0.966060,0.674754,1115.744044
min,5.490000e+02,1.000000,-122.700455,-41.330428,0.000000e+00,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,3.600075e+06,1.000000,-43.225469,12.902646,6.000000e+01,0.000000,0.000000,0.000000,2.000000,4.000000,150.000000
50%,7.900186e+06,30.000000,73.758624,25.270021,2.500000e+02,0.000000,0.000000,0.000000,3.000000,4.200000,328.000000
75%,1.714692e+07,215.000000,79.832568,32.749289,6.000000e+02,0.000000,1.000000,0.000000,3.000000,4.500000,649.000000
max,1.904028e+07,216.000000,175.310552,55.976980,2.500002e+07,1.000000,1.000000,1.000000,4.000000,4.900000,41333.000000

# Perguntas de Negócio

### 1. Qual o nome do restaurante que possui a maior quantidade de avaliações?

In [13]:
restaurante_qtd_av = df.groupby('restaurant_name')['votes'].sum().sort_values(ascending=False).reset_index(name='Maior Quantidade de Avaliacoes').iloc[0]
nome = restaurante_qtd_av['restaurant_name']
qtd_avaliacoes = restaurante_qtd_av['Maior Quantidade de Avaliacoes']

print(f'O restaurante com a maior quantidade de avaliacoes é {nome}, com {qtd_avaliacoes} registros')

O restaurante com a maior quantidade de avaliacoes é Domino's Pizza, com 59749 registros

### 2. Qual o nome do restaurante com a maior nota média?

In [14]:
restaurante_maior_media = (df.groupby('restaurant_name')
                           .agg(
                            maior_quantidade_avaliacoes=('aggregate_rating', 'mean'),
                            menor_id=('restaurant_id', 'min')
                        ).sort_values(by=[ 'maior_quantidade_avaliacoes', 'menor_id' ] , ascending=[False, True]).reset_index().iloc[0]
)
nome = restaurante_maior_media['restaurant_name']
media_av = restaurante_maior_media['maior_quantidade_avaliacoes']

print(f'O restaurante com a maior nota média é {nome}, com {media_av} de nota')

O restaurante com a maior nota média é Indian Grill Room, com 4.9 de nota

### 3. Qual o nome do restaurante que possui o maior valor de uma prato para duas pessoas?

In [15]:
restaurante_valor_dois = df.groupby('restaurant_name')['average_cost_for_two'].max().sort_values(ascending=False).reset_index(name='Maior Valor de Prato').iloc[0]
nome = restaurante_valor_dois['restaurant_name']
maior_valor = restaurante_valor_dois['Maior Valor de Prato']

print(f'O restaurante com o prato mais caro é {nome}, sendo na quantia de {maior_valor}')

O restaurante com o prato mais caro é d'Arry's Verandah Restaurant, sendo na quantia de 25000017

### 4. Qual o nome do restaurante de tipo de culinária brasileira que possui a menor média de avaliação?

In [16]:
df_brasil = (df.loc[(df['country_name'] == 'Brazil') & (df['aggregate_rating'] > 0) , ['restaurant_name', 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
             .agg(
                 media_avaliacoes=('aggregate_rating', 'mean'),
                 menor_id=('restaurant_id', 'min')
             ).sort_values(by=['media_avaliacoes', 'menor_id'] , ascending=[True, True]).reset_index().iloc[0])
nome = df_brasil['restaurant_name']
media_av = df_brasil['media_avaliacoes']

print(f'O restaurante com culinária brasileira e com a menor nota média é o {nome}, com média {media_av}')

O restaurante com culinária brasileira e com a menor nota média é o Natu Sucos, com média 2.3

### 5. Qual o nome do restaurante de tipo de culinária brasileira, e que é do Brasil, que possui a maior média de avaliação?

In [17]:
df_brasil = (df.loc[(df['country_name'] == 'Brazil') & (df['aggregate_rating'] > 0) , ['restaurant_name', 'aggregate_rating', 'restaurant_id']].groupby('restaurant_name')
             .agg(
                 media_avaliacoes=('aggregate_rating', 'mean'),
                 menor_id=('restaurant_id', 'min')
             ).sort_values(by=['media_avaliacoes', 'menor_id'] , ascending=[False, True]).reset_index().iloc[0])
nome = df_brasil['restaurant_name']
media_av = df_brasil['media_avaliacoes']

print(f'O restaurante com culinária brasileira e com a maior nota média é o {nome}, com média {media_av}')

O restaurante com culinária brasileira e com a maior nota média é o Skye - Hotel Unique, com média 4.9

### 6. Os restaurantes que aceitam pedido online são também, na média, os restaurantes que mais possuem avaliações registradas?

In [18]:
media_online = df.loc[df['has_online_delivery'] == 1, 'votes'].mean().round(1)
media_offline = df.loc[df['has_online_delivery'] == 0, 'votes'].mean().round(1)

print(
    f'Os restaurantes com pedidos online têm média de {media_online} avaliações, '
    f'enquanto os sem pedidos online têm {media_offline}'
)
print(f'\nSim, os restaurantes que aceitam pedidos online são os que mais possuem avaliações registradas')

Os restaurantes com pedidos online têm média de 838.8 avaliações, enquanto os sem pedidos online têm 478.3

Sim, os restaurantes que aceitam pedidos online são os que mais possuem avaliações registradas

### 7. Os restaurantes que fazem reservas são também, na média, os restaurantes que possuem o maior valor médio de um prato para duas pessoas?

In [19]:
media_reserva = df.loc[df['has_table_booking'] == 1 , 'average_cost_for_two'].mean().round(1)
media_sem_reserva = df.loc[df['has_table_booking'] == 0, 'average_cost_for_two'].mean().round(1)

print(
    f'Os restaurantes com pedidos reserva têm valor médio de um prato de duas pessoas de {media_reserva}, '
    f'enquanto os sem reserva tem média de valor de {media_sem_reserva}'
)
print(f'\nSim, os restaurantes que fazem reserva possuem o maior valor médio de um prato para duas pessoas')

Os restaurantes com pedidos reserva têm valor médio de um prato de duas pessoas de 69998.4, enquanto os sem reserva tem média de valor de 3482.3

Sim, os restaurantes que fazem reserva possuem o maior valor médio de um prato para duas pessoas

### 8. Os restaurantes do tipo de culinária japonesa dos Estados Unidos da América possuem um valor médio de prato para duas pessoas maior 
### que as churrascarias americanas (BBQ)?

In [20]:
japonesa = df.loc[(df['cuisines'] == 'Japanese') & (df['country_name'] == 'United States of America') , 'average_cost_for_two' ].mean().round(1)
bbq = df.loc[(df['cuisines'] == 'BBQ') & (df['country_name'] == 'United States of America') , 'average_cost_for_two'].mean().round(1)



print(
    f'Os restaurantes do tipo de culinária japonesa dos EUA possuem um valor médio de {japonesa}, '
    f'enquanto os de churrascia (BBQ) possuem {bbq} de valor médio'
)
print(f'\nSim, os restaurantes de culinária japonesa possuem um valor médio de prato para duas pessoas maior que o da churrascaria')

Os restaurantes do tipo de culinária japonesa dos EUA possuem um valor médio de 56.4, enquanto os de churrascia (BBQ) possuem 39.6 de valor médio

Sim, os restaurantes de culinária japonesa possuem um valor médio de prato para duas pessoas maior que o da churrascaria

# Funções de Gráficos

In [21]:
def grafico_online_offline(df):

    media_online = df.loc[df['has_online_delivery'] == 1, 'votes'].mean().round(1)
    media_offline = df.loc[df['has_online_delivery'] == 0, 'votes'].mean().round(1)

    grafico = pd.DataFrame({
        'Tipo': ['Online', 'Offline'],
        'Média de Avaliaçoes': [media_online, media_offline]
    } )

    fig = px.bar(grafico, x='Tipo', y='Média de Avaliaçoes', text='Média de Avaliaçoes', 
                 title='Média de Avaliaçoes: restaurantes com e sem pedidos online', 
                 color='Tipo', color_discrete_map={ 'Online': 'green', 'Offline': 'red'}
)
    fig.update_layout(title_x=0.5)
    fig.update_traces(textposition='outside')

    return fig

grafico_online_offline(df)

In [22]:
def grafico_japao_bbq(df):
    japonesa = df.loc[(df['cuisines'] == 'Japanese') & (df['country_name'] == 'United States of America') , 'average_cost_for_two' ].mean().round(1)
    bbq = df.loc[(df['cuisines'] == 'BBQ') & (df['country_name'] == 'United States of America') , 'average_cost_for_two'].mean().round(1)

    grafico = pd.DataFrame( {
        'Tipo': ['Japonesa', 'BBQ'],
        'Valor Medio Prato para Duas Pessoas': [japonesa, bbq]
    })

    fig = px.bar(grafico, x='Tipo', y='Valor Medio Prato para Duas Pessoas', 
                 title='Valor Médio de Prato para Duas Pessoas: Japonesa x BBQ', 
                 color='Tipo', color_discrete_map={'Japonesa': 'red', 'BBQ': 'orange'},
                 text='Valor Medio Prato para Duas Pessoas')
    
    fig.update_layout(title_x=0.5)
    fig.update_layout(yaxis_title='Valor Médio')
    fig.update_traces(textposition='outside')
    
    return fig

grafico_japao_bbq(df)